---
title: Deep Learning Algorithm Applied to Kaggle Ultrasound Nerve Segmentation
author:
  - name: Peter Gross
    email: pgross@aculocity.com
    affiliation: Aculocity, LLC
    footnote: Corresponding Author
  - name: Warren Allworth
    email: wallworth@aculocity.com
    affiliation: Aculocity, LLC
address:
  - code: Aculocity
    address: Data Department, Oxford Street, Durbanville, Western Cape, 7530
abstract: |
  This paper journals the approach taken to apply Deep Learning neural networks to the domain of identifying nerve endings found in ultrasound scanned images. 
  
  The images were provided through the Kaggle website and was part of a competition closing 18 August 2016 with a prize money of $100 000.

bibliography: mybibfile.bib
output: rticles::elsevier_article
---

_Text based on elsarticle sample manuscript, see [http://www.elsevier.com/author-schemas/latex-instructions#elsarticle](http://www.elsevier.com/author-schemas/latex-instructions#elsarticle)_


The Elsevier article class
==========================

#### Installation

A mathematical formula 

$x^y$

$$\cos (2\theta) = \cos^2 \theta - \sin^2 \theta$$

\begin{equation} \label{eq:someequation}
 f(x)=(x+a)(x+b)
\end{equation}

this references the equation \ref{eq:someequation}.

Reference is made to [@ESLII].


If the document class *elsarticle* is not available on your computer,
you can download and install the system package *texlive-publishers*
(Linux) or install the LaTeX package *elsarticle* using the package
manager of your TeX installation, which is typically TeX Live or MikTeX.

#### Usage

Once the package is properly installed, you can use the document class
*elsarticle* to create a manuscript. Please make sure that your
manuscript follows the guidelines in the Guide for Authors of the
relevant journal. It is not necessary to typeset your manuscript in
exactly the same way as an article, unless you are submitting to a
camera-ready copy (CRC) journal.

#### Functionality

The Elsevier article class is based on the standard article class and
supports almost all of the functionality of that class. In addition, it
features commands and options to format the

-   document style

-   baselineskip

-   front matter

-   keywords and MSC codes

-   theorems, definitions and proofs

-   lables of enumerations

-   citation style and labeling.

Front matter
============

The author names and affiliations could be formatted in two ways:

(1) Group the authors per affiliation.

(2) Use footnotes to indicate the affiliations.

See the front matter of this document for examples. You are recommended
to conform your choice to the journal you are submitting to.

Bibliography styles
===================

There are various bibliography styles available. You can select the
style of your choice in the preamble of this document. These styles are
Elsevier styles based on standard styles like Harvard and Vancouver.
Please use BibTeX to generate your bibliography and include DOIs
whenever available.

Here are two sample references: @Feynman1963118 [@Dirac1953888].

References {#references .unnumbered}
==========
